- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/cask
    homebrew_packages:
      - { name: openssl }
    homebrew_cask_packages:
      - { name: iterm2 }
  tasks:
    - name: add homeberew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps
